In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6]) #одномерный массив
print(a.dtype) #тип всех элементов в массиве
print(a) #вывод всех элементов массива
print(a[0]) #вывод 0 элемента
print(a.shape) #размерность в каждом измерении
print(a.ndim) #количество измерений



int64
[1 2 3 4 5 6]
1
(6,)
1


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6]) #одномерный массив
print(a) #вывод всех элементов массива
print(a[1:3]) #вывод 1-3 элемент, 3 элемент не включительно


int64
[1 2 3 4 5 6]
[2 3]
(6,)
1


In [9]:
b = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]]) #одномерный массив
print(b.dtype) #тип всех элементов в массиве
print(b) #вывод всех элементов массива
print(b[0]) #вывод первой строки
print(b[0][0]) #вывод элемента
print(b.shape) #размерность в каждом измерении
print(b.ndim) #количество измерений


int64
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[1 2 3 4 5 6]
1
(3, 6)
2


In [ ]:
b = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]]) #одномерный массив
print(b) #вывод всех элементов массива
print(b[1:2]) #вывод 1-2 строки, 2 не включительно 
print(b[1:2,1:3]) #вывод 1-3 элементов не включая 3 во второй сторке

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 7  8  9 10 11 12]]
[[8 9]]


In [15]:
c = np.zeros((3, 3)) #одномерный массив
print(c.dtype) #тип всех элементов в массиве
print(c) #вывод всех элементов массива
print(c.shape) #размерность в каждом измерении
print(c.ndim) #количество измерений

float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
2


In [16]:
d = np.ones((3, 3), dtype="int64") #одномерный массив
print(d.dtype) #тип всех элементов в массиве
print(d) #вывод всех элементов массива
print(d.shape) #размерность в каждом измерении
print(d.ndim) #количество измерений

int64
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(3, 3)
2


In [19]:
e = np.arange(4)
print(e)

[0 1 2 3]


In [21]:
f = np.arange(1, 9)
print(f)

[1 2 3 4 5 6 7 8]


In [22]:
g = np.arange(1, 9, 2)
print(g)

[1 3 5 7]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 3], [4, 5]])
print(a)
print(a * 3) #умножение всех элементов на 3
print(a + 3) #сложение всех элементов на 3
print(a * b) #элемент из а умножается на элемент из b

[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]
[[4 5]
 [6 7]]
[[ 2  6]
 [12 20]]


In [34]:
print(a.mean()) #среднее
print(a.max()) #максимальный элемент
print(a.min()) #минимальный элемент
print(a.argmax()) #индекс максималнього элемента
print(a.argmin()) #индекс минимального элемента

2.5
4
1
3
0
